development:
  adapter: postgresql
  encoding: unicode
  database: webpage_development
  pool: 5
  username: postgres
  password: password
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: webpage_test
  pool: 5
  username: postgres
  password: password
  host: localhost


production:
  adapter: postgresql
  encoding: unicode
  database: webpage_production
  pool: 5
  username: postgres
  password: password